### PR TITLE
survey0: fix occasional SIGSEGV in resp0_ctx_recv() when surveyor closes pipe

### PR DESCRIPTION
**Pull request by aleksejsolovev**
resp0_ctx_recv() occasionally got NULL msg from pipe receive aio, because resp0_pipe_close() didn't remove the pipe from socket's recvpipes list, as it rep0_pipe_close() does.
Added test shows the issue, ending up with SIGSEGV without fix proposed.

### CODE REVIEW

**Comment by gdamore** [comment]
Thank you for your contribution.  The core fix you made looks correct to me.  It seems that your tests are failing probably due to leaks in the test code itself.  Please look at the test results and try to address.  If you can't get to it, let me know and I'll see if I can get it over the finish line.

**Comment by aleksejsolovev** [comment]
Thank you for your patience. I'm very sorry for submitting incompletely tested PR. I've reproduced my test code failure with address sanitizing on my local system and fixed memory leak [there](https://github.com/nanomsg/nng/pull/1955/commits/12f3442301104f68338b80b7f17f33f1d62d8c5d). For now I couldn't reproduce none.supplemental.websocket_test failure in mbed-tls pipeline because of outdated mbed-tls library on my local system. I'll try to update it and find out more.

**Comment by gdamore** [comment]
Don't worry about the websocket bug.  Its a problem not related to your code, and I'm working on a fix.

**Comment by aleksejsolovev** [comment]
Thank you. Should I open github issue, squash into one commit with issue id filled in its comment, and reopen PR?

**Pull request closed without merging**
