### PR TITLE
Add C++ test program, proving C++ consumers work.

### PR DESCRIPTION
**Pull request by gdamore**

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
[amd64](http://ci.appveyor.com/project/nanomsg/nng/build/0.0.393)? or x64? I will be interested to see what got generated for a project file as compared/contrasted with what the IDE thinks. Assuming, *vcvarsall.bat x64*, as well as */machine:x64*.

**Comment by gdamore** [comment]
Both 32 and 64 bit builds are tested.  This is driven by the CMake target, and you can see both targets tested in AppVeyor.  amd64 is a synonym for x64, so that's irrelevant.

**Comment by gdamore** [comment]
Well somehow code coverage isn't working -- probably gcov and C++ not happy together.  I need a little time to resolve it.

**Comment by mwpowellhtx** [comment]
I'm not as concerned about gcov, per se. Let me know when it's resolved and I can pull.

**Comment by gdamore** [comment]
Merged.  You can pull from master.

**Pull request merged**
